version: "3.8"
name: qorum

services:
  postgres:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: backend
    ports:
      - "5432:5432"